# Generated by Django 3.0.8 on 2020-07-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileobject',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
