# Generated by Django 3.0.8 on 2020-07-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox_file', '0002_auto_20200715_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileobject',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
